# Generated by Django 2.1.3 on 2018-11-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='aired',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='Ongoing', max_length=120),
        ),
        migrations.AlterField(
            model_name='anime',
            name='views',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.URLField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
