# Generated by Django 2.1.3 on 2018-11-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_anime_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
